services:
  web:
    build: .
    container_name: django_exercise_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media           # persists uploaded files
      - ./db.sqlite3:/app/db.sqlite3 # persists SQLite database
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"
